#ifndef FILEEXAMPLE_CPPLIBPLUGIN_GLOBAL_H
#define FILEEXAMPLE_CPPLIBPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(FILEEXAMPLE_CPPLIBPLUGIN_LIBRARY)
#define FILEEXAMPLE_CPPLIBPLUGIN_EXPORT Q_DECL_EXPORT
#else
#define FILEEXAMPLE_CPPLIBPLUGIN_EXPORT Q_DECL_IMPORT
#endif

#endif // FILEEXAMPLE_CPPLIBPLUGIN_GLOBAL_H
